name: Validator

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate JSON
      run: |
        python .github/scripts/validator.py
        if [ "$?" -ne 0 ]; then
           echo "Script run failed"
           exit 1
        fi
